# Generated by Django 3.1.2 on 2020-10-19 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_habit_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='users',
        ),
        migrations.AddField(
            model_name='habit',
            name='users',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
